#python 3.5
#取出所有汽车参数字段
import codecs
import urllib.request
response = urllib.request.urlopen('http://car.autohome.com.cn/config/series/3788.html')
html =str(response.read(),'gb2312')


import re

regex=re.compile('{"name":".*?","valueitems"')
result=regex.findall(html)

content=''
for string in result:
    content=content+string+"\n"


content=re.sub('{"name":".*?","configitems":\[','',content)
content=re.sub('{"name":".*?","paramitems":\[','',content)

f=codecs.open('D:/demo.txt','w','utf-8')
f.write(content)
f.close()

print(content)


# {"name":"车型名称","valueitems"
# {"name":"厂商指导价(元)","valueitems"
# {"name":"厂商","valueitems"
# {"name":"级别","valueitems"
# {"name":"发动机","valueitems"
# {"name":"变速箱","valueitems"
# {"name":"长*宽*高(mm)","valueitems"
# {"name":"车身结构","valueitems"
# {"name":"最高车速(km/h)","valueitems"
# {"name":"官方0-100km/h加速(s)","valueitems"
# {"name":"实测0-100km/h加速(s)","valueitems"
# {"name":"实测100-0km/h制动(m)","valueitems"
# {"name":"实测油耗(L/100km)","valueitems"
# {"name":"工信部综合油耗(L/100km)","valueitems"
# {"name":"实测离地间隙(mm)","valueitems"
# {"name":"整车质保","valueitems"
# {"name":"长度(mm)","valueitems"
# {"name":"宽度(mm)","valueitems"
# {"name":"高度(mm)","valueitems"
# {"name":"轴距(mm)","valueitems"
# {"name":"前轮距(mm)","valueitems"
# {"name":"后轮距(mm)","valueitems"
# {"name":"最小离地间隙(mm)","valueitems"
# {"name":"整备质量(kg)","valueitems"
# {"name":"车身结构","valueitems"
# {"name":"车门数(个)","valueitems"
# {"name":"座位数(个)","valueitems"
# {"name":"油箱容积(L)","valueitems"
# {"name":"行李厢容积(L)","valueitems"
# {"name":"发动机型号","valueitems"
# {"name":"排量(mL)","valueitems"
# {"name":"排量(L)","valueitems"
# {"name":"进气形式","valueitems"
# {"name":"气缸排列形式","valueitems"
# {"name":"气缸数(个)","valueitems"
# {"name":"每缸气门数(个)","valueitems"
# {"name":"压缩比","valueitems"
# {"name":"配气机构","valueitems"
# {"name":"缸径(mm)","valueitems"
# {"name":"行程(mm)","valueitems"
# {"name":"最大马力(Ps)","valueitems"
# {"name":"最大功率(kW)","valueitems"
# {"name":"最大功率转速(rpm)","valueitems"
# {"name":"最大扭矩(N・m)","valueitems"
# {"name":"最大扭矩转速(rpm)","valueitems"
# {"name":"发动机特有技术","valueitems"
# {"name":"燃料形式","valueitems"
# {"name":"燃油标号","valueitems"
# {"name":"供油方式","valueitems"
# {"name":"缸盖材料","valueitems"
# {"name":"缸体材料","valueitems"
# {"name":"环保标准","valueitems"
# {"name":"简称","valueitems"
# {"name":"挡位个数","valueitems"
# {"name":"变速箱类型","valueitems"
# {"name":"驱动方式","valueitems"
# {"name":"四驱形式","valueitems"
# {"name":"中央差速器结构","valueitems"
# {"name":"前悬架类型","valueitems"
# {"name":"后悬架类型","valueitems"
# {"name":"助力类型","valueitems"
# {"name":"车体结构","valueitems"
# {"name":"前制动器类型","valueitems"
# {"name":"后制动器类型","valueitems"
# {"name":"驻车制动类型","valueitems"
# {"name":"前轮胎规格","valueitems"
# {"name":"后轮胎规格","valueitems"
# {"name":"备胎规格","valueitems"
# {"name":"主/副驾驶座安全气囊","valueitems"
# {"name":"前/后排侧气囊","valueitems"
# {"name":"前/后排头部气囊(气帘)","valueitems"
# {"name":"膝部气囊","valueitems"
# {"name":"胎压监测装置","valueitems"
# {"name":"零胎压继续行驶","valueitems"
# {"name":"安全带未系提示","valueitems"
# {"name":"ISOFIX儿童座椅接口","valueitems"
# {"name":"发动机电子防盗","valueitems"
# {"name":"车内中控锁","valueitems"
# {"name":"遥控钥匙","valueitems"
# {"name":"无钥匙启动系统","valueitems"
# {"name":"无钥匙进入系统","valueitems"
# {"name":"ABS防抱死","valueitems"
# {"name":"制动力分配(EBD/CBC等)","valueitems"
# {"name":"刹车辅助(EBA/BAS/BA等)","valueitems"
# {"name":"牵引力控制(ASR/TCS/TRC等)","valueitems"
# {"name":"车身稳定控制(ESC/ESP/DSC等)","valueitems"
# {"name":"上坡辅助","valueitems"
# {"name":"自动驻车","valueitems"
# {"name":"陡坡缓降","valueitems"
# {"name":"可变悬架","valueitems"
# {"name":"空气悬架","valueitems"
# {"name":"可变转向比","valueitems"
# {"name":"前桥限滑差速器/差速锁","valueitems"
# {"name":"中央差速器锁止功能","valueitems"
# {"name":"后桥限滑差速器/差速锁","valueitems"
# {"name":"电动天窗","valueitems"
# {"name":"全景天窗","valueitems"
# {"name":"运动外观套件","valueitems"
# {"name":"铝合金轮圈","valueitems"
# {"name":"电动吸合门","valueitems"
# {"name":"侧滑门","valueitems"
# {"name":"电动后备厢","valueitems"
# {"name":"感应后备厢","valueitems"
# {"name":"车顶行李架","valueitems"
# {"name":"真皮方向盘","valueitems"
# {"name":"方向盘调节","valueitems"
# {"name":"方向盘电动调节","valueitems"
# {"name":"多功能方向盘","valueitems"
# {"name":"方向盘换挡","valueitems"
# {"name":"方向盘加热","valueitems"
# {"name":"方向盘记忆","valueitems"
# {"name":"定速巡航","valueitems"
# {"name":"前/后驻车雷达","valueitems"
# {"name":"倒车视频影像","valueitems"
# {"name":"行车电脑显示屏","valueitems"
# {"name":"全液晶仪表盘","valueitems"
# {"name":"HUD抬头数字显示","valueitems"
# {"name":"座椅材质","valueitems"
# {"name":"运动风格座椅","valueitems"
# {"name":"座椅高低调节","valueitems"
# {"name":"腰部支撑调节","valueitems"
# {"name":"肩部支撑调节","valueitems"
# {"name":"主/副驾驶座电动调节","valueitems"
# {"name":"第二排靠背角度调节","valueitems"
# {"name":"第二排座椅移动","valueitems"
# {"name":"后排座椅电动调节","valueitems"
# {"name":"电动座椅记忆","valueitems"
# {"name":"前/后排座椅加热","valueitems"
# {"name":"前/后排座椅通风","valueitems"
# {"name":"前/后排座椅按摩","valueitems"
# {"name":"第三排座椅","valueitems"
# {"name":"后排座椅放倒方式","valueitems"
# {"name":"前/后中央扶手","valueitems"
# {"name":"后排杯架","valueitems"
# {"name":"GPS导航系统","valueitems"
# {"name":"定位互动服务","valueitems"
# {"name":"中控台彩色大屏","valueitems"
# {"name":"蓝牙/车载电话","valueitems"
# {"name":"车载电视","valueitems"
# {"name":"后排液晶屏","valueitems"
# {"name":"220V/230V电源","valueitems"
# {"name":"外接音源接口","valueitems"
# {"name":"CD支持MP3/WMA","valueitems"
# {"name":"多媒体系统","valueitems"
# {"name":"扬声器品牌","valueitems"
# {"name":"扬声器数量","valueitems"
# {"name":"近光灯","valueitems"
# {"name":"远光灯","valueitems"
# {"name":"日间行车灯","valueitems"
# {"name":"自适应远近光","valueitems"
# {"name":"自动头灯","valueitems"
# {"name":"转向辅助灯","valueitems"
# {"name":"转向头灯","valueitems"
# {"name":"前雾灯","valueitems"
# {"name":"大灯高度可调","valueitems"
# {"name":"大灯清洗装置","valueitems"
# {"name":"车内氛围灯","valueitems"
# {"name":"前/后电动车窗","valueitems"
# {"name":"车窗防夹手功能","valueitems"
# {"name":"防紫外线/隔热玻璃","valueitems"
# {"name":"后视镜电动调节","valueitems"
# {"name":"后视镜加热","valueitems"
# {"name":"内/外后视镜自动防眩目","valueitems"
# {"name":"后视镜电动折叠","valueitems"
# {"name":"后视镜记忆","valueitems"
# {"name":"后风挡遮阳帘","valueitems"
# {"name":"后排侧遮阳帘","valueitems"
# {"name":"后排侧隐私玻璃","valueitems"
# {"name":"遮阳板化妆镜","valueitems"
# {"name":"后雨刷","valueitems"
# {"name":"感应雨刷","valueitems"
# {"name":"空调控制方式","valueitems"
# {"name":"后排独立空调","valueitems"
# {"name":"后座出风口","valueitems"
# {"name":"温度分区控制","valueitems"
# {"name":"车内空气调节/花粉过滤","valueitems"
# {"name":"车载冰箱","valueitems"
# {"name":"自动泊车入位","valueitems"
# {"name":"发动机启停技术","valueitems"
# {"name":"并线辅助","valueitems"
# {"name":"车道偏离预警系统","valueitems"
# {"name":"主动刹车/主动安全系统","valueitems"
# {"name":"整体主动转向系统","valueitems"
# {"name":"夜视系统","valueitems"
# {"name":"中控液晶屏分屏显示","valueitems"
# {"name":"自适应巡航","valueitems"
# {"name":"全景摄像头","valueitems"